apiVersion: v1
data:
  nginx.conf: |
    server {
      listen 8081;
      server_name _;
      # if ($http_x_forwarded_proto = "http") {
      #     return 301 https://$host$request_uri;
      # }
      location / {
        proxy_set_header X-Forwarded-Proto https;
        proxy_pass http://localhost:8080;
        proxy_set_header Host $host;
        proxy_redirect off;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
      }
      location /health {
        return 200 "healthy\n";
        add_header Content-Type text/plain;
      }
    }
kind: ConfigMap
metadata:
  labels:
    app: airflow
  name: airflow-nginx
  namespace: airflow
