apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: airflow
  name: airflow-logs
  namespace: airflow
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
