apiVersion: v1
kind: Service
metadata:
  labels:
    app: airflow
  name: mariadb-101-rhel7
spec:
  ports:
  - name: 3306-tcp
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: airflow
    component: mariadb
  sessionAffinity: None
  type: ClusterIP
